export default {
  ON_BOARDING_SCREEN: 'ON_BOARDING_SCREEN',
  UNLOCK_SCREEN: 'UNLOCK_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  TODO_LISTING: 'TODO_LISTING',
};
